/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Max
 */
public class frm_Login extends javax.swing.JFrame {
    //frm_Bienvenido x = new frm_Bienvenido();
    public static int c = 0;
    /**
     * Creates new form Login
     */
    public frm_Login() {
        initComponents();
        this.setLocationRelativeTo(null);

        lbl_salir.setBackground(new Color(0, 153, 153));
        txt_usuario.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_cerrar = new javax.swing.JLabel();
        lbl_minimizar = new javax.swing.JLabel();
        Login_Panel = new javax.swing.JPanel();
        txt_usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_contrasenia = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_logo_user = new javax.swing.JLabel();
        lbl_logo_password = new javax.swing.JLabel();
        lbl_ingresar = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_mensaje = new javax.swing.JLabel();
        lbl_salir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        lbl_cerrar.setBackground(new java.awt.Color(0, 153, 153));
        lbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn-cerrar.png"))); // NOI18N
        lbl_cerrar.setOpaque(true);
        lbl_cerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseMoved(evt);
            }
        });
        lbl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseReleased(evt);
            }
        });

        lbl_minimizar.setBackground(new java.awt.Color(0, 153, 153));
        lbl_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn-minimizar.png"))); // NOI18N
        lbl_minimizar.setOpaque(true);
        lbl_minimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_minimizarMouseMoved(evt);
            }
        });
        lbl_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_minimizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_minimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        Login_Panel.setBackground(new java.awt.Color(255, 255, 255));

        txt_usuario.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        txt_contrasenia.setBorder(null);

        lbl_logo_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lbl-user1.png"))); // NOI18N

        lbl_logo_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lbl-pass.png"))); // NOI18N

        lbl_ingresar.setBackground(new java.awt.Color(0, 153, 153));
        lbl_ingresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ingresar.setText("INGRESAR");
        lbl_ingresar.setOpaque(true);
        lbl_ingresar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_ingresarMouseMoved(evt);
            }
        });
        lbl_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ingresarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ingresarMouseExited(evt);
            }
        });

        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lbl-user.png"))); // NOI18N

        lbl_salir.setBackground(new java.awt.Color(0, 153, 153));
        lbl_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_salir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_salir.setText("SALIR");
        lbl_salir.setOpaque(true);
        lbl_salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_salirMouseMoved(evt);
            }
        });
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Login_PanelLayout = new javax.swing.GroupLayout(Login_Panel);
        Login_Panel.setLayout(Login_PanelLayout);
        Login_PanelLayout.setHorizontalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addComponent(lbl_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_logo_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_logo_password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_usuario)
                                .addComponent(jSeparator1)
                                .addComponent(txt_contrasenia)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGap(42, 42, 42))
        );
        Login_PanelLayout.setVerticalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Login_PanelLayout.createSequentialGroup()
                        .addComponent(lbl_logo_user, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_logo_password)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Login_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_cerrarMouseClicked

    private void lbl_cerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseMoved
        // TODO add your handling code here:
        lbl_cerrar.setBackground(Color.red);
    }//GEN-LAST:event_lbl_cerrarMouseMoved

    private void lbl_cerrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbl_cerrarMouseDragged

    private void lbl_cerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseReleased

    }//GEN-LAST:event_lbl_cerrarMouseReleased

    private void lbl_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseExited
        // TODO add your handling code here:
        Color c = new Color(0, 153, 153);
        lbl_cerrar.setBackground(c);
    }//GEN-LAST:event_lbl_cerrarMouseExited

    private void lbl_minimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizarMouseMoved
        // TODO add your handling code here:
        lbl_minimizar.setBackground(Color.blue);
    }//GEN-LAST:event_lbl_minimizarMouseMoved

    private void lbl_minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizarMouseExited
        // TODO add your handling code here:
        lbl_minimizar.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_lbl_minimizarMouseExited

    private void lbl_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(1);
    }//GEN-LAST:event_lbl_minimizarMouseClicked

    private void lbl_ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ingresarMouseExited
        // TODO add your handling code here:
        lbl_ingresar.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_lbl_ingresarMouseExited

    
    private void esperar(){
        
        try {
            this.hide();
            //JOptionPane.showMessageDialog(null, "Bienvenido!!!");
          
            Thread.sleep(2000);
            System.exit(0);
 
        } catch (InterruptedException ex) {
            Logger.getLogger(frm_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void lbl_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ingresarMouseClicked
        // TODO add your handling code here:
        
        if(txt_usuario.getText().equals("admin") && txt_contrasenia.getText().equals("1234")){
            frm_main x = new frm_main();
            x.show(true);
            this.hide();
        }else{
            lbl_mensaje.setText("Usuario/Contraseña invalido(s)\n Intento("+c+")");
            txt_usuario.setText("");
            txt_contrasenia.setText("");
            txt_usuario.requestFocus(true);
            c++;
        }
        if(c == 3){
            //frm_HastaLuego x = new frm_HastaLuego();
            //this.hide();
            //x.show(true);
            System.exit(0);
         
          
            
                     
        }

    }//GEN-LAST:event_lbl_ingresarMouseClicked

    private void lbl_ingresarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ingresarMouseMoved
        // TODO add your handling code here:
        lbl_ingresar.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_lbl_ingresarMouseMoved

    private void lbl_salirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseMoved
        // TODO add your handling code here:
        lbl_salir.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_lbl_salirMouseMoved

    private void lbl_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseExited
        // TODO add your handling code here:
        lbl_salir.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_lbl_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_cerrar;
    private javax.swing.JLabel lbl_ingresar;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_logo_password;
    private javax.swing.JLabel lbl_logo_user;
    private javax.swing.JLabel lbl_mensaje;
    private javax.swing.JLabel lbl_minimizar;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JPasswordField txt_contrasenia;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
