/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panelesMenu;

import frames.frm_TipoArea;
import frames.frm_empleado;

/**
 *
 * @author Max
 */
public class pnl_rrhh extends javax.swing.JPanel {

    /**
     * Creates new form pnl_rrhh
     */
    public pnl_rrhh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nuevo_empleado = new javax.swing.JLabel();
        lbl_nuevo_tipoArea = new javax.swing.JLabel();

        lbl_nuevo_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo_Rempleado.png"))); // NOI18N
        lbl_nuevo_empleado.setText("Nuevo Empleado");
        lbl_nuevo_empleado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_nuevo_empleadoMouseMoved(evt);
            }
        });
        lbl_nuevo_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_nuevo_empleadoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_nuevo_empleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_nuevo_empleadoMousePressed(evt);
            }
        });

        lbl_nuevo_tipoArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipo_area_1.png"))); // NOI18N
        lbl_nuevo_tipoArea.setText("  Nuevo Tipo Area  ");
        lbl_nuevo_tipoArea.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_nuevo_tipoAreaMouseMoved(evt);
            }
        });
        lbl_nuevo_tipoArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_nuevo_tipoAreaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_nuevo_tipoAreaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_nuevo_tipoAreaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lbl_nuevo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(lbl_nuevo_tipoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nuevo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nuevo_tipoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_nuevo_empleadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_empleadoMouseMoved
        // TODO add your handling code here:
        lbl_nuevo_empleado.setSize(205, 90);
    }//GEN-LAST:event_lbl_nuevo_empleadoMouseMoved

    private void lbl_nuevo_empleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_empleadoMouseExited
        // TODO add your handling code here:
        lbl_nuevo_empleado.setSize(195, 80);
    }//GEN-LAST:event_lbl_nuevo_empleadoMouseExited

    private void lbl_nuevo_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_empleadoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbl_nuevo_empleadoMouseClicked

    private void lbl_nuevo_tipoAreaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_tipoAreaMouseMoved
        // TODO add your handling code here:
        lbl_nuevo_tipoArea.setSize(205, 90);
    }//GEN-LAST:event_lbl_nuevo_tipoAreaMouseMoved

    private void lbl_nuevo_tipoAreaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_tipoAreaMouseExited
        // TODO add your handling code here:
        lbl_nuevo_tipoArea.setSize(195, 80);
    }//GEN-LAST:event_lbl_nuevo_tipoAreaMouseExited

    private void lbl_nuevo_tipoAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_tipoAreaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbl_nuevo_tipoAreaMouseClicked

    private void lbl_nuevo_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_empleadoMousePressed
        // TODO add your handling code here:
        frm_empleado x = new frm_empleado();
        x.show(true);
    }//GEN-LAST:event_lbl_nuevo_empleadoMousePressed

    private void lbl_nuevo_tipoAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_tipoAreaMousePressed
        // TODO add your handling code here:
        frm_TipoArea x = new frm_TipoArea();
        x.show(true);
    }//GEN-LAST:event_lbl_nuevo_tipoAreaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_nuevo_empleado;
    private javax.swing.JLabel lbl_nuevo_tipoArea;
    // End of variables declaration//GEN-END:variables
}
