/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panelesMenu;

/**
 *
 * @author Max
 */
public class pnl_venta extends javax.swing.JPanel {

    /**
     * Creates new form pnl_venta
     */
    public pnl_venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nuevo_envio = new javax.swing.JLabel();

        lbl_nuevo_envio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nuevo_envio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo_envio.png"))); // NOI18N
        lbl_nuevo_envio.setText("  Nuevo Envio");
        lbl_nuevo_envio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_nuevo_envioMouseMoved(evt);
            }
        });
        lbl_nuevo_envio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_nuevo_envioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lbl_nuevo_envio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(602, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lbl_nuevo_envio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_nuevo_envioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_envioMouseMoved
        // TODO add your handling code here:
        lbl_nuevo_envio.setSize(190, 90);
    }//GEN-LAST:event_lbl_nuevo_envioMouseMoved

    private void lbl_nuevo_envioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nuevo_envioMouseExited
        // TODO add your handling code here:
        lbl_nuevo_envio.setSize(180, 80);

    }//GEN-LAST:event_lbl_nuevo_envioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_nuevo_envio;
    // End of variables declaration//GEN-END:variables
}
